MicroBarChart - Integrade custom maxvalue
SAP/ui5-webcomponents-react pull request #1281
Opened 2021-02-10 13:34 UTC by ArneBuetergerds

In the MircoBarChart component the value bar is limited by the max dataset value.

To customize the max value of the bar I integrade the optional property customMaxValue as an number.

To ensure that the values of the dataset will be shown correctly the customMaxValue has to be higher as the maxDatasetValue.

2021-02-10 13:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/ui5-webcomponents-react?pullRequest=1281) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/ui5-webcomponents-react?pullRequest=1281) before we can accept your contribution.<br/><hr/>**Arne Bütergerds** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/ui5-webcomponents-react?pullRequest=1281) it.</sub>

2021-02-10 14:29 UTC, Lukas742 requested changes
Hi @ArneBuetergerds 

thanks for creating this PR. :) 

I would even take it a step further and let the user fully control the `maxValue` when the prop is set. Therefore, it should also be possible to pass a number that is smaller than the maximum value of the data set.

2021-02-10 14:29 UTC, Lukas742 commented on packages/charts/src/components/MicroBarChart/MicroBarChart.tsx
> +  customMaxValue?: number;
Please rename the prop to `maxValue` as this explains more that the user is in full control over the max value of the `MicroBarChart`.

2021-02-10 14:29 UTC, Lukas742 commented on packages/charts/src/components/MicroBarChart/MicroBarChart.tsx
> +  */
Please also mention that if this prop is not set, the maximum value is equal to the highest number of the corresponding accessor in the dataset.

2021-02-10 14:29 UTC, Lukas742 commented on packages/charts/src/components/MicroBarChart/MicroBarChart.tsx
> +      return customMaxValue && customMaxValue > maxDatasetValue ? customMaxValue : maxDatasetValue;
As the user should be in full control over the `maxValue` prop, this can be simplified:
```js
      return props.maxValue ?? maxDatasetValue;
```

2021-02-11 08:07 UTC, ArneBuetergerds commented
HI @Lukas742.

You are right. I changed the code with an new commit.

2021-02-11 09:19 UTC, Lukas742 commented
@ArneBuetergerds looks good, thanks.

Could you sign the CLI? After that we are good to merge.

2021-02-15 11:18 UTC, ArneBuetergerds commented
@Lukas742, i finally figured out my problem with the cla. Now it`s signed.

2021-02-15 13:40 UTC, Lukas742 approved these changes

2021-02-15 13:41 UTC, merged

2021-02-15 13:42 UTC, Lukas742 commented
Hi @ArneBuetergerds 

thanks for the contribution, the changes will be available with our next release :)