fix(Modals): support React 18 by rendering Portals instead of creating new roots
SAP/ui5-webcomponents-react pull request #2932
Opened 2022-05-10 14:59 UTC by MarcusNotheis

Fixes #2730

2022-05-11 08:33 UTC, Lukas742 requested changes

2022-05-11 08:33 UTC, Lukas742 commented on packages/main/src/components/Modals/Modals.stories.mdx
> +| `props`       | All supported `Popover` props (see table below). Open will always be set to `true`.    |
```suggestion
| `props`       | All supported `Popover` props (see table below).`open` will always be set to `true`.    |
```

2022-05-11 08:33 UTC, Lukas742 commented on packages/main/src/components/Modals/Modals.stories.mdx
> +| `props`       | All supported `ResponsivePopover` props (see table below). Open will always be set to `true`.    |
```suggestion
| `props`       | All supported `ResponsivePopover` props (see table below). `open` will always be set to `true`.    |
```

2022-05-11 08:33 UTC, Lukas742 commented on packages/main/src/components/Modals/Modals.stories.mdx
> +| `props`       | All supported `MessageBox` props (see table below). Open will always be set to `true`.    |
```suggestion
| `props`       | All supported `MessageBox` props (see table below). `open` will always be set to `true`.    |
```

2022-05-11 08:33 UTC, Lukas742 commented on packages/main/src/components/Modals/Modals.stories.mdx
> +| `props`       | All supported `Dialog` props (see table below). Open will always be set to `true`.    |
```suggestion
| `props`       | All supported `Dialog` props (see table below). `open` will always be set to `true`.    |
```

2022-05-11 12:58 UTC, MarcusNotheis commented on packages/main/src/components/Modals/ModalsProvider.tsx
> +      return [...state, action.payload as ModalState];
not really because the payload of `UpdateModalStateAction` can either be a ModalState or just the ID

2022-05-24 14:30 UTC, MarcusNotheis commented on packages/main/src/components/ActionSheet/__snapshots__/ActionSheet.test.tsx.snap
> +  Object {
I have no idea to be honest 😅

2022-05-24 14:38 UTC, merged