feat(ObjectPageSection & ObjectPageSubSection): add multiple props
SAP/ui5-webcomponents-react pull request #3946
Opened 2023-01-05 10:49 UTC by Lukas742

This PR adds the following props:

__ObjectPageSection:__
- hideTitleText
- titleTextLevel
- wrapTitleText
- header

__ObjectPageSubSection:__
- hideTitleText
- titleTextLevel
- titleTextUppercase

The changes are also improving styling and scroll behavior.

2023-01-23 16:23 UTC, MarcusNotheis approved these changes

2023-01-24 14:06 UTC, Lukas742 commented on cypress/support/commands.tsx
> +  cy.get('[ui5-tabcontainer]').shadow().findByText(tabName).click(clickOptions);
Replaced with respective `cypress-commands` query

2023-01-24 14:06 UTC, Lukas742 commented on cypress/support/commands.tsx
> +  cy.get('[ui5-tabcontainer]').shadow().get(`[aria-posinset="${ariaPosinset}"] [ui5-button]`).click(clickOptions);
Replaced with respective `cypress-commands` query

2023-01-24 14:48 UTC, MarcusNotheis requested changes

2023-01-24 14:48 UTC, MarcusNotheis commented on packages/main/src/components/ObjectPage/ObjectPage.cy.tsx
> +  it.only('single section', () => {
no only :) 
```suggestion
  it('single section', () => {
```

2023-01-24 15:35 UTC, MarcusNotheis approved these changes

2023-01-24 15:39 UTC, merged