refactor: always use named icon import
SAP/ui5-webcomponents-react pull request #4101
Opened 2023-02-06 17:51 UTC by MarcusNotheis

2023-02-06 21:38 UTC, Lukas742 approved these changes

2023-02-06 21:49 UTC, Lukas742 requested changes

2023-02-06 21:49 UTC, Lukas742 commented on packages/main/src/components/Toolbar/OverflowPopover.tsx
> -import { Device, useSyncRef } from '@ui5/webcomponents-react-base';
Please add `useSyncRef` again

2023-02-07 06:50 UTC, MarcusNotheis commented on packages/main/src/components/Toolbar/OverflowPopover.tsx
> -import { Device, useSyncRef } from '@ui5/webcomponents-react-base';
done, thanks

2023-02-07 07:22 UTC, Lukas742 approved these changes

2023-02-07 07:38 UTC, merged