feat(flexbox): introduce flexbox `gap` property
SAP/ui5-webcomponents-react pull request #5002
Opened 2023-08-24 05:37 UTC by marpme

Introduces a new FlexBox property called `gap` that allows users to easily access gap functionality in a standardized way of increasing 16px (=1rem) steps.

Few examples explaining the underlying behaviour:

`gap={1}` will result in 16px gap (=1rem)
`gap={2}` will result in 32px gap (=2rem) etc.

This will ease the different mixtures of gap mechanisms with in projects using UI5.

Alternatively users can also specify full css values in the gap property as string (i.e. "0 2rem") for more advanced usages.

**Thank you for your contribution!** 👏

To get it merged faster, kindly review the checklist below:

## Pull Request Checklist
- [x] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-webcomponents-react/blob/main/CONTRIBUTING.md)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents-react/blob/main/CONTRIBUTING.md#contribute-code) section 
- [x] [Correct commit message style](https://github.com/SAP/ui5-webcomponents-react/blob/main/docs/Guidelines.md#commit-message-style)

2023-08-24 05:40 UTC, marpme commented on packages/main/src/components/FlexBox/FlexBox.cy.tsx
> +    cy.findByTestId('flexbox').should('have.css', 'gap', 'normal');
**Note:** [`normal`](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) should be the default value according to various sources. Therefore, this shall not cause a breaking change for existing components.

2023-08-24 05:45 UTC, marpme commented on packages/main/src/components/FlexBox/FlexBox.jss.ts
> +    gap: ({ gap }: { gap: CSSProperties['gap'] }) => (typeof gap === 'number' ? `${gap}rem` : gap),
**Question:** Shall we consider a different scale for numbers based styles? 

The `gap * 1rem` scaling was the easiest and most straight forward one, that I could come up with at the moment.

2023-09-27 11:30 UTC, Lukas742 requested changes
Thank you for creating this PR :)
I've added a few notes below.

2023-09-27 11:30 UTC, Lukas742 commented on packages/main/src/components/FlexBox/index.tsx
> +   * <b>Note:</b> Corresponds to `gap` property of the CSS specification.
```suggestion
   * **Note:** Corresponds to `gap` property of the CSS specification.
```

2023-12-02 07:29 UTC, closed without merging