Updated Readme
SAP/ui5-webcomponents-react pull request #700
Opened 2020-10-03 03:59 UTC by davidsturgeon

Lerna Link in tags in readme was incorrect and pointed to a broken site. Updated the link with github reference to Lerna.

**Thank you for your contribution!** 👏

To get it merged faster, kindly review the checklist below:

## Pull Request Checklist
- [ ] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md#contribute-code) section 
- [ ] [Correct commit message style](https://github.com/SAP/ui5-webcomponents-react/blob/master/docs/Guidelines.md#commit-message-style)

2020-10-03 03:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/ui5-webcomponents-react?pullRequest=700) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/ui5-webcomponents-react?pullRequest=700) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/ui5-webcomponents-react?pullRequest=700) it.</sub>

2020-10-03 04:09 UTC, justinjrussell commented on README.md
> +  <a href="https://github.com/lerna/lerna" target="_blank">
Please use the correct url https://lerna.js.org

2020-10-04 06:44 UTC, MarcusNotheis requested changes
Thanks for this PR, good catch! As @justinjrussell already mentioned, could you please use the lerna website as link target instead of the github repo?
And you would need to sign the CLA, then we are good to merge :)

2020-10-04 06:44 UTC, MarcusNotheis commented on README.md
> +  <a href="https://github.com/lerna/lerna" target="_blank">
```suggestion
  <a href="https://lerna.js.org" target="_blank">
```

2020-11-06 09:59 UTC, MarcusNotheis approved these changes

2020-11-06 10:19 UTC, merged