Converted dev scripts to ESM modules
SAP/ui5-webcomponents-react pull request #720
Opened 2020-10-08 19:01 UTC by KolCrooks

I converted the dev scripts to ESM modules as talked about in #701.

2020-10-08 19:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/ui5-webcomponents-react?pullRequest=720) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/ui5-webcomponents-react?pullRequest=720) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/ui5-webcomponents-react?pullRequest=720) it.</sub>

2020-10-15 13:59 UTC, MarcusNotheis commented
Hey @KolCrooks,
could you update your branch with the latest master version (or give me write access to that branch in case there are more commits that have to be merged)? Then we can get this into our codebase.
Thanks!

2020-10-15 14:49 UTC, MarcusNotheis requested changes
It looks like jest serializers have to be in `cjs` format, so could you please revert the changes in both serializers (marked as PR comment) and rename them to use the `.cjs` file extension?
Then you have to update the imports in `config/jestsetup.ts` to match the new `.cjs` file extension:
```js
import contentLoaderSerializer from '@shared/tests/serializer/content-loader-serializer.cjs';
import jssSerializer from '@shared/tests/serializer/jss-snapshot-serializer.cjs';
```
Other than that everything looks good and we can merge this PR as soon as all CI jobs are passing.

Thanks!

2020-10-15 14:49 UTC, MarcusNotheis commented on shared/tests/serializer/content-loader-serializer.js
> +}
Could you please reset those changes and rename the file to use the `.cjs` extension?

2020-10-15 14:49 UTC, MarcusNotheis commented on shared/tests/serializer/jss-snapshot-serializer.js
> +}
Could you please reset those changes and rename the file to use the `.cjs` extension?

2020-10-22 09:45 UTC, MarcusNotheis approved these changes

2020-10-22 09:46 UTC, merged

2020-10-22 15:32 UTC, KolCrooks commented
@MarcusNotheis I'm sorry that I haven't been able to work on this / not giving a heads up. I got hit with a ton of work and midterms from uni so It has been tough for me to find time to do things like this.

2020-10-22 19:02 UTC, MarcusNotheis commented
Key @KolCrooks,
No worries, all good - as it was only a very little change that was pending I just added and merged it :) thanks for your work on that PR and good luck for your midterms :)

Best regards,
Marcus