docs: Add JSDoc comments to Page component
SAP/ui5-webcomponents-react pull request #736
Opened 2020-10-15 15:55 UTC by dulcehc

**Thank you for your contribution!** 👏

To get it merged faster, kindly review the checklist below:

## Pull Request Checklist
- [ X] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md#contribute-code) section 
- [ X] [Correct commit message style](https://github.com/SAP/ui5-webcomponents-react/blob/master/docs/Guidelines.md#commit-message-style)

2020-10-15 15:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/ui5-webcomponents-react?pullRequest=736) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/ui5-webcomponents-react?pullRequest=736) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/ui5-webcomponents-react?pullRequest=736) it.</sub>

2020-10-16 09:31 UTC, MarcusNotheis requested changes

2020-10-16 09:31 UTC, MarcusNotheis commented on packages/main/src/components/Page/index.tsx
> +   * The (optional) custom header of this page. Use this aggregation only when a custom header
```suggestion
   * The (optional) custom header of this page. Use this prop only when a custom header
```
`aggregation` is in my opinion very tightly coupled to UI5, I would prefer `prop` here is it's more the "react-way"

2020-10-16 09:31 UTC, MarcusNotheis commented on packages/main/src/components/Page/index.tsx
> +   * The page has three distinct areas that can hold content - a header, content area and a footer.
```suggestion
   * The content area of the page.
```
footer and header are separate props, so content area is the only which is left here

2020-10-16 09:31 UTC, MarcusNotheis commented on packages/main/src/components/Page/index.tsx
> + * A container control that holds one whole screen of an application.
```suggestion
 * A layout component that holds one whole screen of an application.
```
I think layout component is also more the "react-way" of describing it.

2020-10-16 13:53 UTC, dulcehc commented
thanks @MarcusNotheis for your review, I have updated the PR

2020-10-16 13:55 UTC, MarcusNotheis approved these changes

2020-10-19 06:09 UTC, merged