filterBar test update
SAP/ui5-webcomponents-react pull request #917
Opened 2020-11-06 20:45 UTC by sidram05

transition from enzyme to rect-testing-library

**Thank you for your contribution!** 👏

To get it merged faster, kindly review the checklist below:

## Pull Request Checklist
- [ ] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md#contribute-code) section 
- [ ] [Correct commit message style](https://github.com/SAP/ui5-webcomponents-react/blob/master/docs/Guidelines.md#commit-message-style)

2020-11-06 20:46 UTC, sidram05 commented
Hi @MarcusNotheis,

Please could you have a look 

Thanks
Sid

2020-11-07 07:09 UTC, MarcusNotheis requested changes

2020-11-07 07:09 UTC, MarcusNotheis commented on packages/main/src/components/FilterBar/FilterBar.test.tsx
> +    const filterItemsDialog = asFragment.find('ui5-dialog').find(FilterGroupItem);
This whole thing can be removed and replaced with:
```js
    fireEvent.click(screen.getByText('Filters'));

    const [selectFilterBar, selectFilterDialog] = screen.getAllByText('SELECT');
    expect(selectFilterDialog).toHaveAttribute('required', 'true');
    expect(selectFilterDialog.parentNode.parentNode.parentNode.parentNode.querySelector('ui5-checkbox')).toHaveAttribute('disabled', 'true');
```

In the end, that test should look like:
```js
it('Group Filter Items mounted in Dialog', () => {
    render(
      // ... leave the render content as it is
    );

    fireEvent.click(screen.getByText('Filters'));

    const [selectFilterBar, selectFilterDialog] = screen.getAllByText('SELECT');
    expect(selectFilterDialog).toHaveAttribute('required', 'true');
    expect(selectFilterDialog.parentNode.parentNode.parentNode.parentNode.querySelector('ui5-checkbox')).toHaveAttribute('disabled', 'true');
  });
```

2020-11-09 08:34 UTC, MarcusNotheis approved these changes
Hey @sidram05,
that was the last test using `enzyme` - thank you very much for your efforts to help us migrating towards `react-testing-library`, that really helped us a lot :) 

Best regards,
Marcus

2020-11-09 08:36 UTC, merged

2020-11-15 03:05 UTC, sidram05 commented
> Hey @sidram05,
> that was the last test using `enzyme` - thank you very much for your efforts to help us migrating towards `react-testing-library`, that really helped us a lot :)
> 
> Best regards,
> Marcus

Hi @MarcusNotheis, 

Thanks for all the help and guidance !
This my first OSS contribution.
Was a pleasure working with you.

Regards
Siddarth