Lazy Loading @ TodoListPagination
SAP/ui5-webcomponents-react pull request #961
Opened 2020-11-17 19:54 UTC by LuisValgoi

**Thank you for your contribution!** 👏

To get it merged faster, kindly review the checklist below:

## Pull Request Checklist
- [x] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md#contribute-code) section 
- [x] [Correct commit message style](https://github.com/SAP/ui5-webcomponents-react/blob/master/docs/Guidelines.md#commit-message-style)

2020-11-18 17:49 UTC, MarcusNotheis requested changes
I think lazy loading components would add more value in the router, e.g. load every route only when it is really needed, especially for "error" routes like Buggy, Not Found or Not Authorized.

2020-11-18 19:28 UTC, LuisValgoi commented
@MarcusNotheis can you double check?

2020-11-20 12:26 UTC, MarcusNotheis requested changes

2020-11-20 12:26 UTC, MarcusNotheis commented on packages/cra-template-seed/template/src/pages/Todo/List/TodoList.js
> +import React, { lazy, Suspense } from 'react';
please remove those unused imports

2020-11-20 13:58 UTC, MarcusNotheis approved these changes

2020-11-20 13:59 UTC, merged